// <auto-generated />
using System;
using BPCloud.VendorMasterService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BPCloud.VendorMasterService.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20200415081726_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BPCloud.VendorMasterService.Models.CBPApp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CCode");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Level");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("Type");

                    b.Property<string>("User");

                    b.HasKey("ID");

                    b.ToTable("cbp_app");
                });

            modelBuilder.Entity("BPCloud.VendorMasterService.Models.CBPBank", b =>
                {
                    b.Property<string>("BankCode");

                    b.Property<string>("BankCity");

                    b.Property<string>("BankCountry");

                    b.Property<string>("BankName");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("BankCode");

                    b.ToTable("cbp_bank");
                });

            modelBuilder.Entity("BPCloud.VendorMasterService.Models.CBPDepartment", b =>
                {
                    b.Property<string>("Department");

                    b.Property<string>("Language");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Text");

                    b.HasKey("Department", "Language");

                    b.ToTable("cbp_dept");
                });

            modelBuilder.Entity("BPCloud.VendorMasterService.Models.CBPIdentity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DocReq");

                    b.Property<DateTime?>("ExpDateReq");

                    b.Property<string>("Format");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.ToTable("cbp_id");
                });

            modelBuilder.Entity("BPCloud.VendorMasterService.Models.CBPPostal", b =>
                {
                    b.Property<string>("PostalCode");

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("State");

                    b.HasKey("PostalCode");

                    b.ToTable("cbp_postal");
                });

            modelBuilder.Entity("BPCloud.VendorMasterService.Models.CBPTitle", b =>
                {
                    b.Property<string>("Title");

                    b.Property<string>("Language");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("TitleText");

                    b.HasKey("Title", "Language");

                    b.HasAlternateKey("Language", "Title");

                    b.ToTable("cbp_title");
                });

            modelBuilder.Entity("BPCloud.VendorMasterService.Models.CBPType", b =>
                {
                    b.Property<string>("Type");

                    b.Property<string>("Language");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Text");

                    b.HasKey("Type", "Language");

                    b.HasAlternateKey("Language", "Type");

                    b.ToTable("cbp_type");
                });
#pragma warning restore 612, 618
        }
    }
}
